# Generated by Django 5.2.8 on 2025-11-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_instructor_bio_instructor_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='website',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='youtube',
        ),
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='experience_years',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instructor',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='learning_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
